<?php
/**
 * ACF Local Field Group — Ear Wax Removal Page
 *
 * Applies to: page-templates/page-ear-wax.php
 * Position:   acf_after_title (requires Classic Editor — see functions.php)
 *
 * Tabs:
 *   1.  Hero
 *   2.  Stats Bar
 *   3.  Common Symptoms
 *   4.  What Is Microsuction
 *   5.  Treatment Comparison
 *   6.  How It Works
 *   7.  NHS Gap
 *   8.  Pricing
 *   9.  Why Choose Us
 *   10. Testimonials
 *   11. FAQ
 *   12. Final CTA
 */

add_action( 'acf/init', function () {

    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( [
        'key'                   => 'group_ear_wax_page',
        'title'                 => 'Ear Wax Removal — Page Content',
        'position'              => 'acf_after_title',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => [ 'the_content' ],
        'active'                => true,

        'location' => [
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/page-ear-wax.php' ] ],
        ],

        'fields' => [

            // ── Tab 1 · Hero ─────────────────────────────────────
            [ 'key' => 'field_ew_tab_hero', 'label' => 'Hero', 'name' => '', 'type' => 'tab' ],
            [
                'key'           => 'field_ew_hero_image',
                'label'         => 'Hero Image',
                'name'          => 'ew_hero_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'instructions'  => 'Right panel on desktop and background on mobile. Minimum 1200 × 800 px.',
            ],
            [
                'key'         => 'field_ew_hero_image_alt',
                'label'       => 'Hero Image Alt Text',
                'name'        => 'ew_hero_image_alt',
                'type'        => 'text',
                'placeholder' => 'Professional ear wax removal by microsuction',
            ],
            [
                'key'         => 'field_ew_hero_badge',
                'label'       => 'Hero Eyebrow Badge',
                'name'        => 'ew_hero_badge',
                'type'        => 'text',
                'placeholder' => 'TympaHealth Certified',
            ],
            [
                'key'         => 'field_ew_hero_headline',
                'label'       => 'Hero Headline (H1)',
                'name'        => 'ew_hero_headline',
                'type'        => 'text',
                'placeholder' => 'Professional ear wax removal by microsuction',
                'instructions' => 'Wrap a word or phrase in <em> to apply the serif accent style.',
            ],
            [
                'key'         => 'field_ew_hero_body',
                'label'       => 'Hero Body Text',
                'name'        => 'ew_hero_body',
                'type'        => 'textarea',
                'rows'        => 3,
                'placeholder' => 'Powered by TympaHealth, our trained clinicians use gentle low-pressure microsuction — the gold standard in ear care. No water, no mess, completely painless with immediate results.',
            ],
            [
                'key'         => 'field_ew_hero_sub_text',
                'label'       => 'Hero Sub Text (below CTAs)',
                'name'        => 'ew_hero_sub_text',
                'type'        => 'text',
                'placeholder' => 'From £49 · Free follow-up included · Same-day appointments',
            ],
            [
                'key'           => 'field_ew_hero_roundel_1',
                'label'         => 'Roundel Badge — Top',
                'name'          => 'ew_hero_roundel_1',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'thumbnail',
                'instructions'  => 'Circular PNG badge displayed at the top of the hero divider. 130 × 130 px.',
            ],
            [
                'key'         => 'field_ew_hero_roundel_1_alt',
                'label'       => 'Roundel Badge — Top Alt Text',
                'name'        => 'ew_hero_roundel_1_alt',
                'type'        => 'text',
                'placeholder' => 'Same Day Appointments',
            ],
            [
                'key'           => 'field_ew_hero_roundel_2',
                'label'         => 'Roundel Badge — Middle',
                'name'          => 'ew_hero_roundel_2',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'thumbnail',
                'instructions'  => 'Circular PNG badge displayed at the centre of the hero divider. 130 × 130 px.',
            ],
            [
                'key'         => 'field_ew_hero_roundel_2_alt',
                'label'       => 'Roundel Badge — Middle Alt Text',
                'name'        => 'ew_hero_roundel_2_alt',
                'type'        => 'text',
                'placeholder' => 'TympaHealth Certified',
            ],
            [
                'key'           => 'field_ew_hero_roundel_3',
                'label'         => 'Roundel Badge — Bottom',
                'name'          => 'ew_hero_roundel_3',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'thumbnail',
                'instructions'  => 'Circular PNG badge displayed at the bottom of the hero divider. 130 × 130 px.',
            ],
            [
                'key'         => 'field_ew_hero_roundel_3_alt',
                'label'       => 'Roundel Badge — Bottom Alt Text',
                'name'        => 'ew_hero_roundel_3_alt',
                'type'        => 'text',
                'placeholder' => '5-Star Rated',
            ],

            // ── Tab 2 · Stats Bar ────────────────────────────────
            [ 'key' => 'field_ew_tab_stats', 'label' => 'Stats Bar', 'name' => '', 'type' => 'tab' ],
            [
                'key'         => 'field_ew_stats_headline',
                'label'       => 'Headline',
                'name'        => 'ew_stats_headline',
                'type'        => 'text',
                'placeholder' => 'Professional Microsuction Treatment',
            ],
            [
                'key'         => 'field_ew_stats_subhead',
                'label'       => 'Sub-headline',
                'name'        => 'ew_stats_subhead',
                'type'        => 'textarea',
                'rows'        => 2,
                'placeholder' => 'The safest and most effective method of ear wax removal, available across our Hampshire locations.',
            ],
            [
                'key'          => 'field_ew_stats',
                'label'        => 'Stat Cards',
                'name'         => 'ew_stats',
                'type'         => 'repeater',
                'min'          => 0,
                'max'          => 4,
                'layout'       => 'table',
                'button_label' => 'Add Stat',
                'instructions' => 'Up to four stat cards. Leave empty to use defaults.',
                'sub_fields'   => [
                    [ 'key' => 'field_ew_stat_value', 'label' => 'Big Value', 'name' => 'value', 'type' => 'text', 'instructions' => 'e.g. "20", "95%+", "Same", "Free"' ],
                    [ 'key' => 'field_ew_stat_label', 'label' => 'Label',     'name' => 'label', 'type' => 'text', 'instructions' => 'e.g. "Minute Appointments"' ],
                ],
            ],

            // ── Tab 3 · Common Symptoms ──────────────────────────
            [ 'key' => 'field_ew_tab_symptoms', 'label' => 'Common Symptoms', 'name' => '', 'type' => 'tab' ],
            [
                'key'         => 'field_ew_symptoms_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_symptoms_eyebrow',
                'type'        => 'text',
                'placeholder' => 'Common Symptoms',
            ],
            [
                'key'         => 'field_ew_symptoms_headline',
                'label'       => 'Headline',
                'name'        => 'ew_symptoms_headline',
                'type'        => 'text',
                'placeholder' => 'Is Ear Wax Affecting Your Daily Life?',
            ],
            [
                'key'         => 'field_ew_symptoms_subhead',
                'label'       => 'Sub-headline',
                'name'        => 'ew_symptoms_subhead',
                'type'        => 'textarea',
                'rows'        => 2,
                'placeholder' => 'Don\'t let blocked ears hold you back. Recognise these common symptoms?',
            ],
            [
                'key'          => 'field_ew_symptoms',
                'label'        => 'Symptom Cards',
                'name'         => 'ew_symptoms',
                'type'         => 'repeater',
                'min'          => 0,
                'max'          => 6,
                'layout'       => 'block',
                'button_label' => 'Add Symptom',
                'instructions' => 'Up to six symptom cards. Icons are driven by card position (1–6) and cannot be changed here.',
                'sub_fields'   => [
                    [ 'key' => 'field_ew_symptom_title', 'label' => 'Title', 'name' => 'title', 'type' => 'text' ],
                    [ 'key' => 'field_ew_symptom_body',  'label' => 'Body',  'name' => 'body',  'type' => 'textarea', 'rows' => 3 ],
                ],
            ],

            // ── Tab 4 · What Is Microsuction ─────────────────────
            [ 'key' => 'field_ew_tab_about', 'label' => 'What Is Microsuction', 'name' => '', 'type' => 'tab' ],
            [
                'key'           => 'field_ew_about_image',
                'label'         => 'Section Image',
                'name'          => 'ew_about_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'instructions'  => 'Right-column photo. Recommended 900 × 600 px.',
            ],
            [
                'key'         => 'field_ew_about_image_alt',
                'label'       => 'Section Image Alt Text',
                'name'        => 'ew_about_image_alt',
                'type'        => 'text',
                'placeholder' => 'Professional ear examination with advanced equipment',
            ],
            [
                'key'         => 'field_ew_about_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_about_eyebrow',
                'type'        => 'text',
                'placeholder' => 'What You Need to Know',
            ],
            [
                'key'         => 'field_ew_about_headline',
                'label'       => 'Headline',
                'name'        => 'ew_about_headline',
                'type'        => 'text',
                'placeholder' => 'What Is Ear Microsuction?',
            ],
            [
                'key'         => 'field_ew_about_body_1',
                'label'       => 'Body — Paragraph 1',
                'name'        => 'ew_about_body_1',
                'type'        => 'textarea',
                'rows'        => 4,
                'placeholder' => 'Ear Microsuction is the safest and most effective way to remove earwax...',
            ],
            [
                'key'         => 'field_ew_about_body_2',
                'label'       => 'Body — Paragraph 2',
                'name'        => 'ew_about_body_2',
                'type'        => 'textarea',
                'rows'        => 3,
                'placeholder' => 'Painless and clean — no water squirted into your ear canal like syringing.',
            ],
            [
                'key'         => 'field_ew_about_stat_1_value',
                'label'       => 'Stat 1 — Value',
                'name'        => 'ew_about_stat_1_value',
                'type'        => 'text',
                'placeholder' => '95%+',
            ],
            [
                'key'         => 'field_ew_about_stat_1_label',
                'label'       => 'Stat 1 — Label',
                'name'        => 'ew_about_stat_1_label',
                'type'        => 'text',
                'placeholder' => 'Success rate with immediate improvement in hearing',
            ],
            [
                'key'         => 'field_ew_about_stat_2_value',
                'label'       => 'Stat 2 — Value',
                'name'        => 'ew_about_stat_2_value',
                'type'        => 'text',
                'placeholder' => 'No Water',
            ],
            [
                'key'         => 'field_ew_about_stat_2_label',
                'label'       => 'Stat 2 — Label',
                'name'        => 'ew_about_stat_2_label',
                'type'        => 'text',
                'placeholder' => 'Dry procedure — no mess, no water squirted into your ears',
            ],

            // ── Tab 5 · Treatment Comparison ─────────────────────
            [ 'key' => 'field_ew_tab_comparison', 'label' => 'Treatment Comparison', 'name' => '', 'type' => 'tab' ],
            [
                'key'         => 'field_ew_comparison_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_comparison_eyebrow',
                'type'        => 'text',
                'placeholder' => 'Treatment Comparison',
            ],
            [
                'key'         => 'field_ew_comparison_headline',
                'label'       => 'Headline',
                'name'        => 'ew_comparison_headline',
                'type'        => 'text',
                'placeholder' => 'How Our Treatment Compares',
            ],
            [
                'key'         => 'field_ew_comparison_subhead',
                'label'       => 'Sub-headline',
                'name'        => 'ew_comparison_subhead',
                'type'        => 'textarea',
                'rows'        => 2,
                'placeholder' => 'See why microsuction is the gold standard for ear wax removal.',
            ],
            [
                'key'          => 'field_ew_comparison_rows',
                'label'        => 'Comparison Rows',
                'name'         => 'ew_comparison_rows',
                'type'         => 'repeater',
                'min'          => 0,
                'max'          => 10,
                'layout'       => 'table',
                'button_label' => 'Add Row',
                'instructions' => 'Leave empty to use the six default rows. Basic HTML allowed in value cells (e.g. ✓ &#10003;).',
                'sub_fields'   => [
                    [ 'key' => 'field_ew_cmp_feature',      'label' => 'Feature',          'name' => 'feature',      'type' => 'text' ],
                    [ 'key' => 'field_ew_cmp_microsuction',  'label' => 'Our Microsuction', 'name' => 'microsuction',  'type' => 'text' ],
                    [ 'key' => 'field_ew_cmp_syringing',     'label' => 'Syringing',        'name' => 'syringing',     'type' => 'text' ],
                    [ 'key' => 'field_ew_cmp_home',          'label' => 'Home Remedies',    'name' => 'home_remedies', 'type' => 'text' ],
                ],
            ],

            // ── Tab 6 · How It Works ─────────────────────────────
            [ 'key' => 'field_ew_tab_how', 'label' => 'How It Works', 'name' => '', 'type' => 'tab' ],
            [
                'key'           => 'field_ew_how_image',
                'label'         => 'Section Image',
                'name'          => 'ew_how_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'instructions'  => 'Left-column photo. Recommended 800 × 600 px (4:3).',
            ],
            [
                'key'         => 'field_ew_how_image_alt',
                'label'       => 'Section Image Alt Text',
                'name'        => 'ew_how_image_alt',
                'type'        => 'text',
                'placeholder' => 'Healthcare professional performing ear examination',
            ],
            [
                'key'         => 'field_ew_how_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_how_eyebrow',
                'type'        => 'text',
                'placeholder' => 'Your Appointment',
            ],
            [
                'key'         => 'field_ew_how_headline',
                'label'       => 'Headline',
                'name'        => 'ew_how_headline',
                'type'        => 'text',
                'placeholder' => 'What to Expect',
            ],
            [
                'key'         => 'field_ew_how_subhead',
                'label'       => 'Sub-headline',
                'name'        => 'ew_how_subhead',
                'type'        => 'textarea',
                'rows'        => 2,
                'placeholder' => 'Each appointment takes roughly 20–30 minutes. Simple, effective treatment in three easy steps.',
            ],
            [
                'key'          => 'field_ew_how_steps',
                'label'        => 'Steps',
                'name'         => 'ew_how_steps',
                'type'         => 'repeater',
                'min'          => 0,
                'max'          => 3,
                'layout'       => 'block',
                'button_label' => 'Add Step',
                'instructions' => 'Up to three steps. Step numbers are generated automatically from position. Leave empty to use defaults.',
                'sub_fields'   => [
                    [ 'key' => 'field_ew_how_step_title',    'label' => 'Title',          'name' => 'title',          'type' => 'text' ],
                    [ 'key' => 'field_ew_how_step_body',     'label' => 'Body',           'name' => 'body',           'type' => 'textarea', 'rows' => 4 ],
                    [ 'key' => 'field_ew_how_step_duration', 'label' => 'Duration Label', 'name' => 'duration_label', 'type' => 'text', 'instructions' => 'e.g. "~10 minutes". Leave empty to hide.' ],
                    [
                        'key'           => 'field_ew_how_step_duration_style',
                        'label'         => 'Duration Pill Style',
                        'name'          => 'duration_style',
                        'type'          => 'select',
                        'choices'       => [ 'blue' => 'Blue', 'green' => 'Green' ],
                        'default_value' => 'blue',
                        'instructions'  => 'Green is used for the "Free follow-up" step.',
                    ],
                ],
            ],
            [
                'key'         => 'field_ew_how_info_banner',
                'label'       => 'Info Banner Text',
                'name'        => 'ew_how_info_banner',
                'type'        => 'textarea',
                'rows'        => 2,
                'placeholder' => 'During examination, HD images & videos are taken to identify any issues beyond wax buildup.',
            ],

            // ── Tab 7 · NHS Gap ──────────────────────────────────
            [ 'key' => 'field_ew_tab_nhs', 'label' => 'NHS Gap', 'name' => '', 'type' => 'tab' ],
            [
                'key'           => 'field_ew_nhs_image',
                'label'         => 'Section Image',
                'name'          => 'ew_nhs_image',
                'type'          => 'image',
                'return_format' => 'url',
                'preview_size'  => 'medium',
                'instructions'  => 'Left-column photo. Recommended 800 × 600 px (4:3).',
            ],
            [
                'key'         => 'field_ew_nhs_image_alt',
                'label'       => 'Section Image Alt Text',
                'name'        => 'ew_nhs_image_alt',
                'type'        => 'text',
                'placeholder' => 'Friendly pharmacist consultation',
            ],
            [
                'key'         => 'field_ew_nhs_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_nhs_eyebrow',
                'type'        => 'text',
                'placeholder' => 'Why Pharmacy Ear Care',
            ],
            [
                'key'         => 'field_ew_nhs_headline',
                'label'       => 'Headline',
                'name'        => 'ew_nhs_headline',
                'type'        => 'text',
                'placeholder' => 'Skip the 12–16 Week NHS Wait',
            ],
            [
                'key'         => 'field_ew_nhs_body_1',
                'label'       => 'Body — Paragraph 1',
                'name'        => 'ew_nhs_body_1',
                'type'        => 'textarea',
                'rows'        => 4,
                'placeholder' => 'In the UK, 3.9% of the population need earwax management yearly...',
            ],
            [
                'key'         => 'field_ew_nhs_body_2',
                'label'       => 'Body — Paragraph 2',
                'name'        => 'ew_nhs_body_2',
                'type'        => 'textarea',
                'rows'        => 4,
                'placeholder' => 'At Southdowns Pharmacy Group, we\'ve partnered with TympaHealth...',
                'instructions' => 'Basic HTML allowed. Use <strong> for emphasis.',
            ],
            [
                'key'         => 'field_ew_nhs_locations_headline',
                'label'       => 'Locations Box Headline',
                'name'        => 'ew_nhs_locations_headline',
                'type'        => 'text',
                'placeholder' => 'Serving across Hampshire:',
            ],
            [
                'key'         => 'field_ew_nhs_locations',
                'label'       => 'Location Pills',
                'name'        => 'ew_nhs_locations',
                'type'        => 'textarea',
                'rows'        => 3,
                'placeholder' => "Emsworth\nHavant\nRowlands Castle",
                'instructions' => 'One location name per line.',
            ],

            // ── Tab 8 · Pricing ──────────────────────────────────
            [ 'key' => 'field_ew_tab_pricing', 'label' => 'Pricing', 'name' => '', 'type' => 'tab' ],
            [
                'key'         => 'field_ew_pricing_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_pricing_eyebrow',
                'type'        => 'text',
                'placeholder' => 'Transparent Pricing',
            ],
            [
                'key'         => 'field_ew_pricing_headline',
                'label'       => 'Headline',
                'name'        => 'ew_pricing_headline',
                'type'        => 'text',
                'placeholder' => 'Ear Wax Removal Pricing',
            ],
            [
                'key'         => 'field_ew_pricing_subhead',
                'label'       => 'Sub-headline',
                'name'        => 'ew_pricing_subhead',
                'type'        => 'textarea',
                'rows'        => 2,
                'placeholder' => 'Clear, upfront pricing with no hidden fees.',
            ],
            [
                'key'         => 'field_ew_pricing_consult_price',
                'label'       => 'Consultation — Price',
                'name'        => 'ew_pricing_consult_price',
                'type'        => 'text',
                'placeholder' => '£10',
                'instructions' => 'Displayed as a large number. Include the £ symbol.',
            ],
            [
                'key'         => 'field_ew_pricing_consult_title',
                'label'       => 'Consultation — Title',
                'name'        => 'ew_pricing_consult_title',
                'type'        => 'text',
                'placeholder' => 'Initial Consultation',
            ],
            [
                'key'         => 'field_ew_pricing_consult_body',
                'label'       => 'Consultation — Body',
                'name'        => 'ew_pricing_consult_body',
                'type'        => 'textarea',
                'rows'        => 3,
                'placeholder' => 'Comprehensive ear assessment before treatment to determine the best care for you.',
            ],
            [
                'key'         => 'field_ew_pricing_consult_bullets',
                'label'       => 'Consultation — Bullet Points',
                'name'        => 'ew_pricing_consult_bullets',
                'type'        => 'textarea',
                'rows'        => 4,
                'placeholder' => "HD ear canal imaging\nSymptom discussion\nTreatment plan explanation",
                'instructions' => 'One bullet per line.',
            ],
            [
                'key'         => 'field_ew_pricing_treatment_price',
                'label'       => 'Treatment — Price',
                'name'        => 'ew_pricing_treatment_price',
                'type'        => 'text',
                'placeholder' => '£49',
                'instructions' => 'Displayed as a large number. Include the £ symbol.',
            ],
            [
                'key'         => 'field_ew_pricing_treatment_title',
                'label'       => 'Treatment — Title',
                'name'        => 'ew_pricing_treatment_title',
                'type'        => 'text',
                'placeholder' => 'Ear Wax Removal',
            ],
            [
                'key'         => 'field_ew_pricing_treatment_body',
                'label'       => 'Treatment — Body',
                'name'        => 'ew_pricing_treatment_body',
                'type'        => 'textarea',
                'rows'        => 3,
                'placeholder' => 'Professional ear wax removal for clear, healthy ears.',
            ],
            [
                'key'         => 'field_ew_pricing_treatment_bullets',
                'label'       => 'Treatment — Bullet Points',
                'name'        => 'ew_pricing_treatment_bullets',
                'type'        => 'textarea',
                'rows'        => 6,
                'placeholder' => "Consultation included\nSame-day appointments\nHearing screening included\nFree 7-day follow-up\nHD imaging before & after",
                'instructions' => 'One bullet per line.',
            ],

            // ── Tab 9 · Why Choose Us ────────────────────────────
            [ 'key' => 'field_ew_tab_why', 'label' => 'Why Choose Us', 'name' => '', 'type' => 'tab' ],
            [
                'key'         => 'field_ew_why_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_why_eyebrow',
                'type'        => 'text',
                'placeholder' => 'Why Us',
            ],
            [
                'key'         => 'field_ew_why_headline',
                'label'       => 'Headline',
                'name'        => 'ew_why_headline',
                'type'        => 'text',
                'placeholder' => 'Why Choose Southdowns Pharmacy',
            ],
            [
                'key'         => 'field_ew_why_subhead',
                'label'       => 'Sub-headline',
                'name'        => 'ew_why_subhead',
                'type'        => 'textarea',
                'rows'        => 2,
                'placeholder' => 'TympaHealth certified clinicians using the latest diagnostic technology for safe, effective ear care.',
            ],
            [
                'key'          => 'field_ew_why_cards',
                'label'        => 'Feature Cards',
                'name'         => 'ew_why_cards',
                'type'         => 'repeater',
                'min'          => 0,
                'max'          => 6,
                'layout'       => 'block',
                'button_label' => 'Add Card',
                'instructions' => 'Up to six feature cards. Icons are driven by card position (1–6) and cannot be changed here. Leave empty to use defaults.',
                'sub_fields'   => [
                    [ 'key' => 'field_ew_why_card_title', 'label' => 'Title', 'name' => 'title', 'type' => 'text' ],
                    [ 'key' => 'field_ew_why_card_body',  'label' => 'Body',  'name' => 'body',  'type' => 'textarea', 'rows' => 4 ],
                ],
            ],

            // ── Tab 10 · Testimonials ────────────────────────────
            [ 'key' => 'field_ew_tab_testimonials', 'label' => 'Testimonials', 'name' => '', 'type' => 'tab' ],
            [
                'key'         => 'field_ew_testimonials_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_testimonials_eyebrow',
                'type'        => 'text',
                'placeholder' => 'Patient Reviews',
            ],
            [
                'key'         => 'field_ew_testimonials_headline',
                'label'       => 'Headline',
                'name'        => 'ew_testimonials_headline',
                'type'        => 'text',
                'placeholder' => 'What Our Patients Say',
            ],
            [
                'key'          => 'field_ew_testimonials',
                'label'        => 'Testimonials',
                'name'         => 'ew_testimonials',
                'type'         => 'repeater',
                'min'          => 0,
                'max'          => 3,
                'layout'       => 'block',
                'button_label' => 'Add Testimonial',
                'instructions' => 'Up to three patient reviews. Leave empty to use defaults.',
                'sub_fields'   => [
                    [ 'key' => 'field_ew_test_initials', 'label' => 'Initials',       'name' => 'initials', 'type' => 'text', 'instructions' => 'e.g. "DW" — shown in the avatar circle.' ],
                    [ 'key' => 'field_ew_test_name',     'label' => 'Full Name',      'name' => 'name',     'type' => 'text' ],
                    [ 'key' => 'field_ew_test_branch',   'label' => 'Branch',         'name' => 'branch',   'type' => 'text', 'instructions' => 'e.g. "Emsworth Branch"' ],
                    [ 'key' => 'field_ew_test_quote',    'label' => 'Quote',          'name' => 'quote',    'type' => 'textarea', 'rows' => 4 ],
                ],
            ],

            // ── Tab 11 · FAQ ─────────────────────────────────────
            [ 'key' => 'field_ew_tab_faq', 'label' => 'FAQ', 'name' => '', 'type' => 'tab' ],
            [
                'key'         => 'field_ew_faq_eyebrow',
                'label'       => 'Eyebrow Text',
                'name'        => 'ew_faq_eyebrow',
                'type'        => 'text',
                'placeholder' => 'FAQs',
            ],
            [
                'key'         => 'field_ew_faq_headline',
                'label'       => 'Headline',
                'name'        => 'ew_faq_headline',
                'type'        => 'text',
                'placeholder' => 'Frequently Asked Questions',
            ],
            [
                'key'         => 'field_ew_faq_intro',
                'label'       => 'Intro Text',
                'name'        => 'ew_faq_intro',
                'type'        => 'textarea',
                'rows'        => 2,
                'placeholder' => 'Everything you need to know about ear wax removal at Southdowns Pharmacy.',
            ],
            [
                'key'         => 'field_ew_faq_rating',
                'label'       => 'Sidebar Stat — Rating',
                'name'        => 'ew_faq_rating',
                'type'        => 'text',
                'placeholder' => '4.9',
            ],
            [
                'key'         => 'field_ew_faq_reviews',
                'label'       => 'Sidebar Stat — Reviews',
                'name'        => 'ew_faq_reviews',
                'type'        => 'text',
                'placeholder' => '400+',
            ],
            [
                'key'         => 'field_ew_faq_patients',
                'label'       => 'Sidebar Stat — Patients',
                'name'        => 'ew_faq_patients',
                'type'        => 'text',
                'placeholder' => '10k+',
            ],
            [
                'key'          => 'field_ew_faqs',
                'label'        => 'FAQ Items',
                'name'         => 'ew_faqs',
                'type'         => 'repeater',
                'min'          => 0,
                'max'          => 0,
                'layout'       => 'block',
                'button_label' => 'Add FAQ',
                'instructions' => 'Leave empty to use the eight default questions. Basic HTML allowed in answers (e.g. <strong>).',
                'sub_fields'   => [
                    [ 'key' => 'field_ew_faq_question', 'label' => 'Question', 'name' => 'question', 'type' => 'text' ],
                    [ 'key' => 'field_ew_faq_answer',   'label' => 'Answer',   'name' => 'answer',   'type' => 'textarea', 'rows' => 5, 'instructions' => 'Basic HTML allowed (e.g. <strong>).' ],
                ],
            ],

            // ── Tab 12 · Final CTA ───────────────────────────────
            [ 'key' => 'field_ew_tab_cta', 'label' => 'Final CTA', 'name' => '', 'type' => 'tab' ],
            [
                'key'         => 'field_ew_cta_trust_pills',
                'label'       => 'Trust Pills',
                'name'        => 'ew_cta_trust_pills',
                'type'        => 'textarea',
                'rows'        => 4,
                'placeholder' => "TympaHealth Certified\nFree Follow-Up\nSame-Day Available\nAges 18+ Only",
                'instructions' => 'One pill label per line.',
            ],
            [
                'key'         => 'field_ew_cta_headline',
                'label'       => 'Headline',
                'name'        => 'ew_cta_headline',
                'type'        => 'text',
                'placeholder' => 'Clearer Hearing Starts Today',
            ],
            [
                'key'         => 'field_ew_cta_body',
                'label'       => 'Body Text',
                'name'        => 'ew_cta_body',
                'type'        => 'textarea',
                'rows'        => 3,
                'placeholder' => 'Don\'t suffer in silence. Book your ear wax removal appointment at one of our TympaHealth-equipped branches and experience immediate relief.',
            ],
            [
                'key'         => 'field_ew_cta_stat_rating',
                'label'       => 'Stat — Average Rating',
                'name'        => 'ew_cta_stat_rating',
                'type'        => 'text',
                'placeholder' => '4.9/5',
            ],
            [
                'key'         => 'field_ew_cta_stat_reviews',
                'label'       => 'Stat — 5-Star Reviews',
                'name'        => 'ew_cta_stat_reviews',
                'type'        => 'text',
                'placeholder' => '400+',
            ],
            [
                'key'         => 'field_ew_cta_stat_patients',
                'label'       => 'Stat — Happy Patients',
                'name'        => 'ew_cta_stat_patients',
                'type'        => 'text',
                'placeholder' => '10,000+',
            ],

        ],
    ] );

} );
